### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by toru-Major** [toru-Major/protospace-33489#1]
# URL
https://protospace-33489.herokuapp.com/

[本番環境のURL](https://dashboard.heroku.com/apps/protospace-33489)

**Comment by tech-oa** [comment]
toru-Majorさん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
◯パスワードは確認用を含めて2回入力すること
→２回目の入力欄に１回目と異なるパスワードを入力したところ、ユーザー登録できてしまいました。

◯ログアウト状態のユーザーは、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページ以外のページに遷移しようとすると、ログインページにリダイレクトされること
→ログアウト状態で編集ページのURLを入力すると、「We're sorry, but something went wrong.
If you are the application owner check the logs for more information.」というエラーが出てログインページにリダイレクトされません。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by toru-Major** [comment]
レビューありがとうございます。該当箇所を修正しフォームで提出させていただきました。

**Comment by tech-oa** [comment]
toru-Majorさん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀

**Comment by toru-Major** [comment]
ありがとうございます！最終課題も引き続きがんばります！
